# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-02 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=200, verbose_name='老实告诉你将学会'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='', max_length=200, verbose_name='课程须知'),
        ),
    ]
